### ISSUE TITLE
finalise() not called on a HtsFile. AND CUDA error: CUBLAS_STATUS_EXECUTION_FAILED during Dorado basecalling

### ISSUE THREAD

**Issue by ebautistas** [nanoporetech/dorado#1086]
Hello

# Issue Report

## Please describe the issue:

I encountered a finalise() not called on a HtsFile and CUBLAS_STATUS_EXECUTION_FAILED error while running Dorado Basecaller on a multi-GPU setup. The basecaller fails during processing, and it appears to be related to a CUDA/CUBLAS operation. Below are the relevant details from my environment and logs.

## Steps to reproduce the issue:

Run Dorado Basecaller with the following configuration:

    GPUs: NVIDIA A800 80GB x4, NVIDIA T1000 8GB
    Dorado Basecaller version: (please specify version)
    CUDA version: 12.3
    Driver version: 545.23.06

The error occurs during basecalling, and the GPU usage remains at 0% while memory allocation happens across multiple GPUs.

## Run environment:
- Dorado version: 0.8.1
- Dorado command: 
dorado basecaller sup,5mCG_5hmCG --min-qscore 10 /data/sample/pod5/ > sample.bam
- Operating system: ubuntu 20.04
- Hardware (CPUs, Memory, GPUs): NVIDIA A800 80GB PCIe (x4), NVIDIA T1000 8GB
- Source data type: pod5

## Logs

[2024-10-16 12:43:12.280] [info] Running: "basecaller" "sup,5mCG_5hmCG" "--min-qscore" "10" "/data/sample/pod5/"
[2024-10-16 12:43:12.539] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v5.0.0 with httplib
[2024-10-16 12:43:18.046] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v5.0.0_5mCG_5hmCG@v2.0.1 with httplib
[2024-10-16 12:43:18.486] [info] > Creating basecall pipeline
[2024-10-16 12:43:24.071] [info] cuda:2 using chunk size 12288, batch size 960
[2024-10-16 12:43:25.003] [info] cuda:1 using chunk size 12288, batch size 960
[2024-10-16 12:43:25.024] [warning] Unable to find chunk benchmarks for GPU "NVIDIA T1000 8GB", model /data/Analysis/Analysis/.temp_dorado_model-48bb98c34a307de9/dna_r10.4.1_e8.2_400bps_sup@v5.0.0 and chunk size 1728. Full benchmarking will run for this device, which may take some time.
[2024-10-16 12:43:25.025] [info] cuda:3 using chunk size 12288, batch size 960
[2024-10-16 12:43:25.054] [info] cuda:2 using chunk size 6144, batch size 960
[2024-10-16 12:43:26.038] [info] cuda:3 using chunk size 6144, batch size 960
[2024-10-16 12:43:26.058] [info] cuda:1 using chunk size 6144, batch size 960
**[2024-10-16 12:43:26.748] [error] finalise() not called on a HtsFile.
[2024-10-16 12:43:26.750] [error] CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`**
Exception raised from gemm<c10::Half> at /pytorch/pyold/aten/src/ATen/cuda/CUDABlas.cpp:427 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f2492bfc9b7 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f248c181115 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #2: <unknown function> + 0xa8fd141 (0x7f2492ac1141 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #3: <unknown function> + 0xa915c7d (0x7f2492ad9c7d in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #4: at::native::structured_mm_out_cuda::impl(at::Tensor const&, at::Tensor const&, at::Tensor const&) + 0x4a (0x7f2492adaeaa in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #5: <unknown function> + 0xa61213d (0x7f24927d613d in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #6: <unknown function> + 0xa6121c0 (0x7f24927d61c0 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #7: at::_ops::mm::call(at::Tensor const&, at::Tensor const&) + 0x161 (0x7f248d6db9c1 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #8: <unknown function> + 0x49f3b05 (0x7f248cbb7b05 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #9: at::native::matmul(at::Tensor const&, at::Tensor const&) + 0x49 (0x7f248cbb7fa9 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #10: <unknown function> + 0x5a58f30 (0x7f248dc1cf30 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #11: at::_ops::matmul::call(at::Tensor const&, at::Tensor const&) + 0x161 (0x7f248d7e0301 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #12: torch::nn::LinearImpl::forward(at::Tensor const&) + 0x100 (0x7f249022af90 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #13: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0xa64168]
frame #14: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0xa6c198]
frame #15: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0xa3f5a2]
frame #16: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0xa7c5e9]
frame #17: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0xa7c718]
frame #18: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0xa796ef]
frame #19: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0xa7b1e7]
frame #20: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0x99ec19]
frame #21: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0x898f27]
frame #22: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0x84825b]
frame #23: <unknown function> + 0x114df (0x7f24876034df in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #24: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0x89932f]
frame #25: /home/prom/Software/dorado-0.8.1-linux-x64/bin/dorado() [0x8553b0]
frame #26: <unknown function> + 0x1196e380 (0x7f2499b32380 in /home/prom/Software/dorado-0.8.1-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #27: <unknown function> + 0x8609 (0x7f24875fa609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #28: clone + 0x43 (0x7f24871b5353 in /lib/x86_64-linux-gnu/libc.so.6)

Any suggestions are appreciated.
Thanks,

**Comment by malton-ont** [comment]
Hi @ebautistas,

`finalise() not called on a HtsFile` generally appears because of a preceding error - it's an indication that a disorderly shutdown occurred, and can be ignored.

That disorderly shutdown is because the T1000 card is not suitable for basecalling. Please use `-x cuda:0,1,2,3` when basecalling on this device.

**Comment by ebautistas** [comment]
> Hi @ebautistas,
> 
> `finalise() not called on a HtsFile` generally appears because of a preceding error - it's an indication that a disorderly shutdown occurred, and can be ignored.
> 
> That disorderly shutdown is because the T1000 card is not suitable for basecalling. Please use `-x cuda:0,1,2,3` when basecalling on this device.

Hello @malton-ont Thank you so much! The basecaller is now working!
