### ISSUE TITLE
strange gpu memory behaviour with dorado 0.9.6 and Batchsize 196 on Tesla V100S-PCIE-32GB

### ISSUE THREAD

**Issue by johannesgeibel** [nanoporetech/dorado#1358]
Hi,
I had some crashed basecalling runs with 0.9.6 on Tesla V100S-PCIE-32GB, resulting in an "CuBLAS error 13" (2/3 which started with batchsize 196/1664). Strangly, other runs finished fine with higher batch sizes up to 320. Therefore, I went back to some small test data and ran dorado 0.9.6 duplex on different limited batch sizes to see, how the GPU behaves.
For the test data, batchsize 192 worked fine, however when running with batchsize 196, the GPU memory was not constant, but increased over time (without resulting in an error, though):

![Image](https://github.com/user-attachments/assets/cc2bd11f-a41a-49c4-82ae-bfafc01dd4ff)

This looks quite strange - do you have any explanations for this behavior?

Thanks,
Johannes

The error log of one of the failed runs:
```
starting time: Wed May 14 11:54:14 CEST 2025
[2025-05-14 11:54:15.282] [info] Running: "duplex" "-v" "-r" "models/dna_r10.4.1_e8.2_400bps_sup@v5.0.0" "/data/users/ms-ag-labwei/nanopore/MGPT/calls/tmp/20250508_1420_P2S-01928-A_PBE34701_085e1916/tmpPod5"
[2025-05-14 11:54:15.310] [info] > No duplex pairs file provided, pairing will be performed automatically
[2025-05-14 11:54:16.030] [debug] > Reads to process: 509675
[2025-05-14 11:54:22.184] [debug] TxEncoderStack: use_koi_tiled false.
[2025-05-14 11:54:22.184] [debug] TxEncoderStack: use_koi_volta_tiled true.
[2025-05-14 11:54:24.253] [debug] cuda:0 memory available: 32.76GB
[2025-05-14 11:54:24.253] [debug] cuda:0 memory limit 28.49GB
[2025-05-14 11:54:24.253] [debug] cuda:0 maximum safe estimated batch size at chunk size 12288 is 352
[2025-05-14 11:54:24.253] [debug] Auto batchsize cuda:0: testing up to 352 in steps of 32
[2025-05-14 11:54:24.255] [info] Calculating optimized batch size for GPU "Tesla V100S-PCIE-32GB" and model dna_r10.4.1_e8.2_400bps_sup@v5.0.0. Full benchmarking will run for this device, which may take some time.
[2025-05-14 11:54:27.440] [debug] Auto batchsize cuda:0: 32, time per chunk 0.647744 ms
[2025-05-14 11:54:27.517] [debug] Auto batchsize cuda:0: 64, time per chunk 0.498768 ms
[2025-05-14 11:54:27.610] [debug] Auto batchsize cuda:0: 96, time per chunk 0.446538 ms
[2025-05-14 11:54:27.732] [debug] Auto batchsize cuda:0: 128, time per chunk 0.441520 ms
[2025-05-14 11:54:27.909] [debug] Auto batchsize cuda:0: 160, time per chunk 0.376863 ms
[2025-05-14 11:54:28.067] [debug] Auto batchsize cuda:0: 192, time per chunk 0.375083 ms
[2025-05-14 11:54:28.248] [debug] Auto batchsize cuda:0: 224, time per chunk 0.386647 ms
[2025-05-14 11:54:28.482] [debug] Auto batchsize cuda:0: 256, time per chunk 0.380932 ms
[2025-05-14 11:54:28.712] [debug] Auto batchsize cuda:0: 288, time per chunk 0.382268 ms
[2025-05-14 11:54:28.968] [debug] Auto batchsize cuda:0: 320, time per chunk 0.379853 ms
[2025-05-14 11:54:29.261] [debug] Auto batchsize cuda:0: 352, time per chunk 0.395715 ms
[2025-05-14 11:54:29.261] [debug] Adding chunk timings to internal cache for GPU Tesla V100S-PCIE-32GB, model dna_r10.4.1_e8.2_400bps_sup@v5.0.0 (6 entries)
[2025-05-14 11:54:29.261] [debug] Largest batch size for cuda:0: 192, time per chunk 0.375083 ms
[2025-05-14 11:54:29.261] [debug] Final batch size for cuda:0[0]: 192
[2025-05-14 11:54:29.261] [info] cuda:0 using chunk size 12288, batch size 192
[2025-05-14 11:54:29.261] [debug] cuda:0 Model memory 13.70GB
[2025-05-14 11:54:29.261] [debug] cuda:0 Decode memory 1.66GB
[2025-05-14 11:54:30.054] [debug] cuda:0 memory available: 32.15GB
[2025-05-14 11:54:30.054] [debug] cuda:0 memory limit 15.07GB
[2025-05-14 11:54:30.054] [debug] cuda:0 maximum safe estimated batch size at chunk size 10000 is 1856
[2025-05-14 11:54:30.054] [debug] Auto batchsize cuda:0: testing up to 1856 in steps of 64
[2025-05-14 11:54:30.054] [info] Calculating optimized batch size for GPU "Tesla V100S-PCIE-32GB" and model dna_r10.4.1_e8.2_5khz_stereo@v1.3. Full benchmarking will run for this device, which may take some time.
[2025-05-14 11:54:30.123] [debug] Auto batchsize cuda:0: 64, time per chunk 0.494160 ms
[2025-05-14 11:54:30.189] [debug] Auto batchsize cuda:0: 128, time per chunk 0.247008 ms
[2025-05-14 11:54:30.256] [debug] Auto batchsize cuda:0: 192, time per chunk 0.171589 ms
[2025-05-14 11:54:30.328] [debug] Auto batchsize cuda:0: 256, time per chunk 0.134180 ms
[2025-05-14 11:54:30.402] [debug] Auto batchsize cuda:0: 320, time per chunk 0.106752 ms
[2025-05-14 11:54:30.474] [debug] Auto batchsize cuda:0: 384, time per chunk 0.091960 ms
[2025-05-14 11:54:30.568] [debug] Auto batchsize cuda:0: 448, time per chunk 0.103175 ms
[2025-05-14 11:54:30.676] [debug] Auto batchsize cuda:0: 512, time per chunk 0.093688 ms
[2025-05-14 11:54:30.777] [debug] Auto batchsize cuda:0: 576, time per chunk 0.085931 ms
[2025-05-14 11:54:30.883] [debug] Auto batchsize cuda:0: 640, time per chunk 0.081501 ms
[2025-05-14 11:54:30.995] [debug] Auto batchsize cuda:0: 704, time per chunk 0.078167 ms
[2025-05-14 11:54:31.110] [debug] Auto batchsize cuda:0: 768, time per chunk 0.074231 ms
[2025-05-14 11:54:31.234] [debug] Auto batchsize cuda:0: 832, time per chunk 0.073169 ms
[2025-05-14 11:54:31.390] [debug] Auto batchsize cuda:0: 896, time per chunk 0.085010 ms
[2025-05-14 11:54:31.547] [debug] Auto batchsize cuda:0: 960, time per chunk 0.080906 ms
[2025-05-14 11:54:31.708] [debug] Auto batchsize cuda:0: 1024, time per chunk 0.077624 ms
[2025-05-14 11:54:31.874] [debug] Auto batchsize cuda:0: 1088, time per chunk 0.075360 ms
[2025-05-14 11:54:32.045] [debug] Auto batchsize cuda:0: 1152, time per chunk 0.073638 ms
[2025-05-14 11:54:32.221] [debug] Auto batchsize cuda:0: 1216, time per chunk 0.071394 ms
[2025-05-14 11:54:32.402] [debug] Auto batchsize cuda:0: 1280, time per chunk 0.069992 ms
[2025-05-14 11:54:32.588] [debug] Auto batchsize cuda:0: 1344, time per chunk 0.066395 ms
[2025-05-14 11:54:32.770] [debug] Auto batchsize cuda:0: 1408, time per chunk 0.063084 ms
[2025-05-14 11:54:32.954] [debug] Auto batchsize cuda:0: 1472, time per chunk 0.061441 ms
[2025-05-14 11:54:33.148] [debug] Auto batchsize cuda:0: 1536, time per chunk 0.060500 ms
[2025-05-14 11:54:33.342] [debug] Auto batchsize cuda:0: 1600, time per chunk 0.059583 ms
[2025-05-14 11:54:33.543] [debug] Auto batchsize cuda:0: 1664, time per chunk 0.058948 ms
[2025-05-14 11:54:33.812] [debug] Auto batchsize cuda:0: 1728, time per chunk 0.076761 ms
[2025-05-14 11:54:34.088] [debug] Auto batchsize cuda:0: 1792, time per chunk 0.075907 ms
[2025-05-14 11:54:34.369] [debug] Auto batchsize cuda:0: 1856, time per chunk 0.074285 ms
[2025-05-14 11:54:34.369] [debug] Adding chunk timings to internal cache for GPU Tesla V100S-PCIE-32GB, model dna_r10.4.1_e8.2_5khz_stereo@v1.3 (19 entries)
[2025-05-14 11:54:34.369] [debug] Largest batch size for cuda:0: 1664, time per chunk 0.058948 ms
[2025-05-14 11:54:34.369] [debug] Final batch size for cuda:0[0]: 1664
[2025-05-14 11:54:34.369] [info] cuda:0 using chunk size 10000, batch size 1664
[2025-05-14 11:54:34.369] [debug] cuda:0 Model memory 9.37GB
[2025-05-14 11:54:34.369] [debug] cuda:0 Decode memory 3.87GB
[2025-05-14 11:54:35.555] [info] > Starting Stereo Duplex pipeline
[2025-05-14 11:54:35.558] [debug] BasecallerNode chunk size 10000
[2025-05-14 11:54:35.558] [debug] Using dorado duplex channel count of 10
[2025-05-14 11:54:35.559] [debug] BasecallerNode chunk size 12288
[2025-05-14 11:54:35.587] [info] > Reading read channel info
[2025-05-14 11:54:36.420] [info] > Processed read channel info
[2025-05-14 12:07:36.931] [warning] Caught Torch error 'CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`', clearing CUDA cache and retrying.
[2025-05-14 12:07:37.526] [error] CuBLAS error 13
```

**Comment by malton-ont** [comment]
Hi @johannesgeibel,

This appears to be an issue in the torch CUDACachingAllocator, which controls memory allocations on the GPU. As we are repeatedly running the same model, torch should be reusing the earlier memory allocations when it requires a new tensor (as the new tensors should exactly match the size of previous allocations). We've seen occasional instances where this doesn't happen correctly, and torch continually allocates new memory without releasing or reusing old allocations. What I think is happening is that a large allocation is partially reused when a new, smaller allocation is required, so now when the next large allocation comes along that should have used that memory block it has to create a new one instead.

One way to adjust this is to set the environment variable `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:250` (you may need to fiddle with that value a bit - dorado defaults to 25 at the moment). Setting this tells torch it isn't allowed to break up existing memory blocks that are larger than 250MB, which seems to help.

**Comment by johannesgeibel** [comment]
Ah - thanks. This resolved it in fact:

![Image](https://github.com/user-attachments/assets/6cf6005a-1da7-470d-bf8d-4d87b3a5ef56)
