### ISSUE TITLE
dorado 0.3.3 duplex CUDA out of memory

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/dorado#326]
Hi

I get an out of memory error when running dorado 0.3.3 duplex basecalling on a machine with 4xA100 GPUs (40GB version). 

Nothing is running on the GPUs before I start the basecalling.

### Command
```
dorado duplex --guard-gpus --device "cuda:all" dna_r10.4.1_e8.2_400bps_sup@v4.2.0 pod5/ > supdup.bam
```
### Error messasge
```
[2023-08-09 13:15:04.555] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-08-09 13:28:28.852] [info] > Starting Stereo Duplex pipeline
[2023-08-09 13:28:28.921] [info] > Reading read channel info
[2023-08-09 13:29:09.436] [info] > Processed read channel info
[2023-08-09 13:29:43.998] [warning] Caught Torch error 'CUDA out of memory. Tried to allocate 22.47 GiB (GPU 1; 39.39 GiB total capacity; 17.26 GiB already allocated; 4.07 GiB free; 34.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF', clearing CUDA cache and retrying.
terminate called after throwing an instance of 'c10::OutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 22.47 GiB (GPU 1; 39.39 GiB total capacity; 16.70 GiB already allocated; 4.63 GiB free; 34.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /pytorch/pyold/c10/cuda/CUDACachingAllocator.cpp:913 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f24afc1ea77 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #1: <unknown function> + 0xa9f8705 (0x7f24afbde705 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #2: <unknown function> + 0xa9f89fe (0x7f24afbde9fe in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #3: <unknown function> + 0xa9f8d8e (0x7f24afbded8e in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #4: <unknown function> + 0x4530be1 (0x7f24a9716be1 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #5: at::detail::empty_generic(c10::ArrayRef<long>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType, c10::optional<c10::MemoryFormat>) + 0x14 (0x7f24a9710624 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #6: at::detail::empty_cuda(c10::ArrayRef<long>, c10::ScalarType, c10::optional<c10::Device>, c10::optional<c10::MemoryFormat>) + 0x111 (0x7f24adb68fc1 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #7: at::detail::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x31 (0x7f24adb69291 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #8: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x1f (0x7f24adc1066f in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #9: <unknown function> + 0xa61a3f9 (0x7f24af8003f9 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #10: <unknown function> + 0xa61a4db (0x7f24af8004db in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #11: at::_ops::empty_memory_format::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xe7 (0x7f24aa57c707 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #12: <unknown function> + 0x56c71af (0x7f24aa8ad1af in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #13: at::_ops::empty_memory_format::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x1b2 (0x7f24aa5bc942 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #14: /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64//bin/dorado() [0x857a6f]
frame #15: /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64//bin/dorado() [0x85d899]
frame #16: /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64//bin/dorado() [0x87d376]
frame #17: /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64//bin/dorado() [0x8a1428]
frame #18: /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64//bin/dorado() [0x8572bd]
frame #19: /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64//bin/dorado() [0x8faa48]
frame #20: /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64//bin/dorado() [0x8fb23f]
frame #21: <unknown function> + 0x1196e440 (0x7f24b6b54440 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.3-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #22: <unknown function> + 0x81ca (0x7f24a400b1ca in /lib64/libpthread.so.0)
frame #23: clone + 0x43 (0x7f24a3348e73 in /lib64/libc.so.6)

/var/spool/slurmd/job1420677/slurm_script: line 33: 335702 Aborted                 (core dumped) $DORADO duplex --guard-gpus --device "cuda:all" $CONFIG $INPUTDIR > $OUTPUTDIR/supdup.$FLOWCELLID.$MODEL.bam
```

**Comment by tijyojwad** [comment]
Hi @Kirk3gaard - sorry about this issue, we're looking into it with highest priority.

**Comment by hborga** [comment]
I'm having the same issue running duplex with dorado 0.3.3 

```
terminate called after throwing an instance of 'c10::OutOfMemoryError'
  what():  CUDA out of memory.
```

**Comment by tijyojwad** [comment]
We have a potential fix for the issue. @Kirk3gaard @hborga would you be willing to give this build a try? https://cdn.oxfordnanoportal.com/software/analysis/dorado/preview/dorado-0.3.4-rc1-linux-x64.tar.gz

**Comment by mattloose** [comment]
Unfortunately I am seeing the same error on version 0.3.4-rc1.

For those on this thread I was able to work around the issue on 0.3.3 by calling on a single GPU and setting a low batch size of 64. Presumably that reduces the performance of the basecaller by some amount in addition to the loss of performance of one vs many GPUs.

**Comment by Kirk3gaard** [comment]
Tried 0.3.4 and it also causes an out of memory error.

`[2023-08-10 08:45:33.611] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-08-10 09:02:18.120] [info] > Starting Stereo Duplex pipeline
[2023-08-10 09:02:18.195] [info] > Reading read channel info
[2023-08-10 09:03:15.323] [info] > Processed read channel info
terminate called after throwing an instance of 'c10::OutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 8.66 GiB (GPU 2; 39.39 GiB total capacity; 31.57 GiB already allocated; 7.24 GiB free; 31.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /pytorch/pyold/c10/cuda/CUDACachingAllocator.cpp:913 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f6053d3ca77 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #1: <unknown function> + 0xa9f8705 (0x7f6053cfc705 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #2: <unknown function> + 0xa9f89fe (0x7f6053cfc9fe in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #3: <unknown function> + 0xa9f8d8e (0x7f6053cfcd8e in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #4: <unknown function> + 0x4530be1 (0x7f604d834be1 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #5: at::detail::empty_generic(c10::ArrayRef<long>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType, c10::optional<c10::MemoryFormat>) + 0x14 (0x7f604d82e624 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #6: at::detail::empty_cuda(c10::ArrayRef<long>, c10::ScalarType, c10::optional<c10::Device>, c10::optional<c10::MemoryFormat>) + 0x111 (0x7f6051c86fc1 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #7: at::detail::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x31 (0x7f6051c87291 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #8: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x1f (0x7f6051d2e66f in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #9: <unknown function> + 0xa61a3f9 (0x7f605391e3f9 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #10: <unknown function> + 0xa61a4db (0x7f605391e4db in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #11: at::_ops::empty_memory_format::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xe7 (0x7f604e69a707 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #12: <unknown function> + 0x56c71af (0x7f604e9cb1af in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #13: at::_ops::empty_memory_format::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x1b2 (0x7f604e6da942 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #14: /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64//bin/dorado() [0x857a6f]
frame #15: /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64//bin/dorado() [0x913476]
frame #16: /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64//bin/dorado() [0x8fb348]
frame #17: <unknown function> + 0x1196e440 (0x7f605ac72440 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #18: <unknown function> + 0x81ca (0x7f60481291ca in /lib64/libpthread.so.0)
frame #19: clone + 0x43 (0x7f6047466e73 in /lib64/libc.so.6)

/var/spool/slurmd/job1466857/slurm_script: line 33: 251580 Aborted                 (core dumped) $DORADO duplex --guard-gpus --device "cuda:all" $CONFIG $INPUTDIR > $OUTPUTDIR/supdup.$FLOWCELLID.$MODEL.bam`

**Comment by tijyojwad** [comment]
Hello! We believe we've found the major bug. Here's a build with the fix - https://cdn.oxfordnanoportal.com/software/analysis/dorado/preview/dorado-0.3.4-rc2-linux-x64.tar.gz . Would anyone be interested in testing this out?

**Comment by mattloose** [comment]
Downloading now. Will let you know.

**Comment by mattloose** [comment]
Early signs are promising - it has passed places where it crashed previously. Total run time for this dataset is estimated as 1.5 hours (at 5% in) so I'll keep you posted.

**Comment by mattloose** [comment]
OK - I can confirm that the new cersion above worked on a dataset it had previously failed with.

[2023-08-10 20:20:33.984] [info] > Simplex reads basecalled: 435433
[2023-08-10 20:20:33.984] [info] > Simplex reads filtered: 52
[2023-08-10 20:20:33.984] [info] > Duplex reads basecalled: 80999
[2023-08-10 20:20:33.984] [info] > Duplex reads filtered: 939
[2023-08-10 20:20:33.984] [info] > Duplex rate: 47.546844%
[2023-08-10 20:20:33.984] [info] > Basecalled @ Bases/s: 2.212259e+06

This was running with two 4090s, no --guard-gpu and allowing auto batch sizes etc.

**Comment by Kirk3gaard** [comment]
Cool. Started basecalling on a 4xA100 node. Will let you know how it goes.

**Comment by tijyojwad** [comment]
Awesome, thanks for confirming!!

**Comment by Kirk3gaard** [comment]
I tried without --guard-gpus and it crashed again. Will let you know if I have more success with this option activated.

`
[2023-08-10 21:31:41.201] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-08-10 21:47:35.982] [info] > Starting Stereo Duplex pipeline
[2023-08-10 21:47:36.080] [info] > Reading read channel info
[2023-08-10 21:48:34.648] [info] > Processed read channel info
[2023-08-10 21:50:24.440] [warning] Caught Torch error 'CUDA out of memory. Tried to allocate 10.91 GiB (GPU 2; 39.39 GiB total capacity; 22.64 GiB already allocated; 3.91 GiB free; 34.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF', clearing CUDA cache and retrying.
terminate called after throwing an instance of 'c10::OutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 10.91 GiB (GPU 2; 39.39 GiB total capacity; 22.64 GiB already allocated; 5.27 GiB free; 33.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /pytorch/pyold/c10/cuda/CUDACachingAllocator.cpp:913 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fcdebb9fa77 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #1: <unknown function> + 0xa9f8705 (0x7fcdebb5f705 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #2: <unknown function> + 0xa9f89fe (0x7fcdebb5f9fe in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #3: <unknown function> + 0xa9f8d8e (0x7fcdebb5fd8e in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #4: <unknown function> + 0x4530be1 (0x7fcde5697be1 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #5: at::detail::empty_generic(c10::ArrayRef<long>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType, c10::optional<c10::MemoryFormat>) + 0x14 (0x7fcde5691624 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #6: at::detail::empty_cuda(c10::ArrayRef<long>, c10::ScalarType, c10::optional<c10::Device>, c10::optional<c10::MemoryFormat>) + 0x111 (0x7fcde9ae9fc1 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #7: at::detail::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x31 (0x7fcde9aea291 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #8: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x1f (0x7fcde9b9166f in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #9: <unknown function> + 0xa61a3f9 (0x7fcdeb7813f9 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #10: <unknown function> + 0xa61a4db (0x7fcdeb7814db in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #11: at::_ops::empty_memory_format::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xe7 (0x7fcde64fd707 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #12: <unknown function> + 0x56c71af (0x7fcde682e1af in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #13: at::_ops::empty_memory_format::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x1b2 (0x7fcde653d942 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #14: /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64//bin/dorado() [0x85315f]
frame #15: /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64//bin/dorado() [0x914ade]
frame #16: /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64//bin/dorado() [0x8fd4e2]
frame #17: /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64//bin/dorado() [0x8fef26]
frame #18: <unknown function> + 0x1196e440 (0x7fcdf2ad5440 in /ceph/hpc/home/eurasmusk/software/dorado-0.3.4-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #19: <unknown function> + 0x81ca (0x7fcddff8c1ca in /lib64/libpthread.so.0)
frame #20: clone + 0x43 (0x7fcddf2c9e73 in /lib64/libc.so.6)

/var/spool/slurmd/job1498353/slurm_script: line 33: 475040 Aborted                 (core dumped) $DORADO duplex --device "cuda:all" $CONFIG $INPUTDIR > $OUTPUTDIR/supdup.$FLOWCELLID.$MODEL.bam
`

**Comment by ymcki** [comment]
I can finish my run with 0.3.4-rc2 without --guard-gpus.

**Comment by tijyojwad** [comment]
Hi @Kirk3gaard - thanks for testing it again. We've prepared another build where we've made some conservative decisions about how much memory to use. Shouldn't affect performance, and likely fixes your problem

https://cdn.oxfordnanoportal.com/software/analysis/dorado/preview/dorado-0.3.4-rc3-linux-x64.tar.gz

**Comment by hborga** [comment]
> Hello! We believe we've found the major bug. Here's a build with the fix - https://cdn.oxfordnanoportal.com/software/analysis/dorado/preview/dorado-0.3.4-rc2-linux-x64.tar.gz . Would anyone be interested in testing this out?

this build worked perfect for me! Thank you

**Comment by palakpsheth** [comment]
@tijyojwad I can confirm that `rc3` works without `--guard-gpus` on NVIDIA GeForce RTX 3060 12GB

**Comment by Kirk3gaard** [comment]
> Hi @Kirk3gaard - thanks for testing it again. We've prepared another build where we've made some conservative decisions about how much memory to use. Shouldn't affect performance, and likely fixes your problem
> 
> https://cdn.oxfordnanoportal.com/software/analysis/dorado/preview/dorado-0.3.4-rc3-linux-x64.tar.gz

Great. I can confirm that the previous one did work with --guard-gpus but was so slow that only 8 GB was basecalled in the 48 hour slurm window with 4xA100 cards. Trying rc3 without it.

**Comment by tijyojwad** [comment]
Hi all - we just released v0.3.4 with the fixes published here earlier. Thank you so much for trying out the rc builds and giving timely feedback! Support from the community is what helps us move fast and deliver the things that are most impactful.

New build links are available here - https://github.com/nanoporetech/dorado#installation

P.S. - @Kirk3gaard I'm closing this issue now. if you still see the perf drop can you open another ticket and we can debug it there?
