### ISSUE TITLE
cuDNN error.....

### ISSUE THREAD

**Issue by tnn111** [nanoporetech/dorado#515]
I just installed 0.5.0 and got the attached (I can supply the whole thing if needed).

I installed the latest binary today.

[2023-12-10 17:46:19.347] [debug] Sorted channel 96
terminate called after throwing an instance of 'c10::CuDNNError'
  what():  cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
Exception raised from run_conv_plan at /pytorch/pyold/aten/src/ATen/native/cudnn/Conv_v8.cpp:203 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fb700b849b7 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #1: <unknown function> + 0x3f1b6a7 (0x7fb6fa0676a7 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #2: <unknown function> + 0x89bf27b (0x7fb6feb0b27b in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #3: <unknown function> + 0x89c00db (0x7fb6feb0c0db in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #4: <unknown function> + 0x89a54ca (0x7fb6feaf14ca in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #5: at::native::cudnn_convolution(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) + 0x96 (0x7fb6feaf1b16 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #6: <unknown function> + 0xa632127 (0x7fb70077e127 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #7: <unknown function> + 0xa6321e0 (0x7fb70077e1e0 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #8: at::_ops::cudnn_convolution::call(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool) + 0x23d (0x7fb6fb673e9d in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #9: at::native::_convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool) + 0x1505 (0x7fb6faa32cf5 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #10: <unknown function> + 0x58a7496 (0x7fb6fb9f3496 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #11: <unknown function> + 0x58a7517 (0x7fb6fb9f3517 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #12: at::_ops::_convolution::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long, bool, bool, bool, bool) + 0x29b (0x7fb6fb2160fb in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #13: at::native::convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long) + 0x21d (0x7fb6faa26d3d in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #14: <unknown function> + 0x58a6f55 (0x7fb6fb9f2f55 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #15: <unknown function> + 0x58a6fbf (0x7fb6fb9f2fbf in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #16: at::_ops::convolution::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<long>, bool, c10::ArrayRef<c10::SymInt>, long) + 0x223 (0x7fb6fb215443 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #17: at::native::conv1d(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) + 0x1c5 (0x7fb6faa29f35 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #18: <unknown function> + 0x5a57b31 (0x7fb6fbba3b31 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #19: at::_ops::conv1d::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long) + 0x20c (0x7fb6fb67198c in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #20: torch::nn::Conv1dImpl::forward(at::Tensor const&) + 0x3a0 (0x7fb6fe17da40 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #21: /global/common/software/m4302/bin/dorado() [0x957686]
frame #22: /global/common/software/m4302/bin/dorado() [0x95836f]
frame #23: /global/common/software/m4302/bin/dorado() [0x95d188]
frame #24: /global/common/software/m4302/bin/dorado() [0x946d80]
frame #25: /global/common/software/m4302/bin/dorado() [0x946ee8]
frame #26: /global/common/software/m4302/bin/dorado() [0x94753c]
frame #27: <unknown function> + 0x1196e380 (0x7fb707aba380 in /global/common/software/m4302/dorado-0.5.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #28: <unknown function> + 0xa6ea (0x7fb6f57e66ea in /lib64/libpthread.so.0)
frame #29: clone + 0x41 (0x7fb6f472149f in /lib64/libc.so.6)

srun: error: nid003845: task 0: Aborted
srun: Terminating StepId=19177975.7

**Comment by vellamike** [comment]
Hi, what command were you  running? Could you also provide information on your  GPU, CPU, OS and RAM?

**Comment by tnn111** [comment]
Hi Mike,

Sorry! 

It was the attached:

#!/bin/bash
#SBATCH -N 8
#SBATCH -C gpu
#SBATCH  --gpus-per-node=4
#SBATCH -q regular
#SBATCH -J SE15A
#SBATCH ***@***.***
#SBATCH --mail-type=ALL
#SBATCH -t 08:00:00
#SBATCH -A m4302

srun -n 1 -c 128 --cpu_bind=cores -G 4 --gpu-bind=none dorado duplex --verbose sup,5mCG_5hmCG,5mC_5hmC,6mA xaa.pod5 > xaa.bam 2> xaa.log &
srun -n 1 -c 128 --cpu_bind=cores -G 4 --gpu-bind=none dorado duplex --verbose sup,5mCG_5hmCG,5mC_5hmC,6mA xab.pod5 > xab.bam 2> xab.log &
srun -n 1 -c 128 --cpu_bind=cores -G 4 --gpu-bind=none dorado duplex --verbose sup,5mCG_5hmCG,5mC_5hmC,6mA xac.pod5 > xac.bam 2> xac.log &
srun -n 1 -c 128 --cpu_bind=cores -G 4 --gpu-bind=none dorado duplex --verbose sup,5mCG_5hmCG,5mC_5hmC,6mA xad.pod5 > xad.bam 2> xad.log &
srun -n 1 -c 128 --cpu_bind=cores -G 4 --gpu-bind=none dorado duplex --verbose sup,5mCG_5hmCG,5mC_5hmC,6mA xae.pod5 > xae.bam 2> xae.log &
srun -n 1 -c 128 --cpu_bind=cores -G 4 --gpu-bind=none dorado duplex --verbose sup,5mCG_5hmCG,5mC_5hmC,6mA xaf.pod5 > xaf.bam 2> xaf.log &
srun -n 1 -c 128 --cpu_bind=cores -G 4 --gpu-bind=none dorado duplex --verbose sup,5mCG_5hmCG,5mC_5hmC,6mA xag.pod5 > xag.bam 2> xag.log &
srun -n 1 -c 128 --cpu_bind=cores -G 4 --gpu-bind=none dorado duplex --verbose sup,5mCG_5hmCG,5mC_5hmC,6mA xah.pod5 > xah.bam 2> xah.log &

wait

**Comment by tnn111** [comment]
And the GPU is an A100. I have been running fine using 0.4.3. It’s a NERSC supercomputer (Perlmutter) with 4 A100s per node.

**Comment by tnn111** [comment]
While the compute nodes have 4 A100s, the head nodes have only 1, but otherwise they are identical. I am running the following on a head node and it’s been fine for ours and produced a BAM file that’s almost 8 GB now:

dorado duplex hac,5mCG_5hmCG,5mC_5hmC,6mA pod5 > Disc1.bam 2> Disc1.log &

The only difference I can see is that it’s “hac” instead of “sup”.

**Comment by vellamike** [comment]
OK - so you you think the issue occurs when running with duplex _and_ `5mCG_5hmCG,5mC_5hmC,6mA` ? Have you ever observed this segfault in a situation where you're not calling duplex plus mod base calling?

**Comment by tnn111** [comment]
> OK - so you you think the issue occurs when running with duplex and 5mCG_5hmCG,5mC_5hmC,6mA ?
> 
Yes.
> Have you ever observed this segfault in a situation where you're not calling duplex plus mod base calling?
> 
No. I ran two large jobs overnight without the mod base calling and both completed without issues.

Any tests I can run?

**Comment by malton-ont** [comment]
@tnn111 - not directly related, but it's not supported to run both `5mCG_5hmCG` and `5mC_5hmC` at the same time. This should not be necessary either - the all-context model will by definition include all sites covered by the CG context.

**Comment by tnn111** [comment]
Thanks! I didn’t think that one through. I have enough GPU cycles to spare right now so I decided to rerun over 100 datasets using 0.5 and all the methylation options I could find. This may indeed be the cause. I’ll retry with just two of the options and hopefully all will be well.

It would be good if this were flagged up front in case anyone else is dumb enough to try it :-)

**Comment by tnn111** [comment]
Thanks again. I tested it and everything now works fine.

**Comment by tijyojwad** [comment]
adding enhancement tag to track the request for flagging incompatible modbase models. we're planning on adding that feature in the next patch release.

**Comment by tijyojwad** [comment]
v0.5.1 (https://github.com/nanoporetech/dorado#installation) now prevents models with overlapping canonical bases from being run simultaneously.
