### ISSUE TITLE
dorado v0.7 CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by pre-mRNA** [nanoporetech/dorado#842]
# Issue Report

## Please describe the issue:

Hi, I've been using Dorado for some time and recently tried the updated v5 models for RNA004 basecalling. 

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

When I basecall reads using the new RNA004 SUP models with modbase calling, Dorado aborts basecalling due to a cuda error. 

## Steps to reproduce the issue:

I use the command: 

./dorado basecaller -v sup,m6A,pseU $data_dir --estimate-poly-a > ${wd}/${name}_dorado_polyA_m6A_unmapped.bam

## Run environment:
- Dorado version: Dorado v0.7.0
- Dorado command: ./dorado basecaller sup,m6A,pseU $data_dir --estimate-poly-a > ${wd}/${name}_dorado_polyA_m6A_unmapped.bam

- Operating system: Linux 
- Hardware (CPUs, Memory, GPUs): 4 x Tesla V100 32GB GPUs
- Source data type: POD5
- Source data location: Networked Lustre filesystem
- Details about data: 3M RNA004 reads, generated on Promethion 
-
## Logs

(base) [user@gadi-gpu-v100-0100 bin]$ ./dorado basecaller -v sup,m6A,pseU $data_dir --estimate-poly-a > ${wd}/${name}_dorado_polyA_m6A_unmapped.bam
[2024-05-25 13:39:37.825] [info] Running: "basecaller" "-v" "sup,m6A,pseU" "/data/20240328_2254_P2S-00909-B_PAU42445_0a472f31/pod5/" "--estimate-poly-a"
[2024-05-25 13:39:38.839] [debug] Found existing simplex model: rna004_130bps_sup@v5.0.0
[2024-05-25 13:39:38.839] [debug] Found existing modification model: rna004_130bps_sup@v5.0.0_m6A@v1
[2024-05-25 13:39:38.839] [debug] Found existing modification model: rna004_130bps_sup@v5.0.0_pseU@v1
[2024-05-25 13:39:38.855] [info] Normalised: overlap 500 -> 492
[2024-05-25 13:39:38.855] [info] > Creating basecall pipeline
[2024-05-25 13:39:38.855] [debug] CRFModelConfig { qscale:1.200000 qbias:2.000000 stride:6 bias:1 clamp:0 out_features:4096 state_len:5 outsize:4096 blank_score:0.000000 scale:1.000000 num_features:1 sample_rate:4000 mean_qscore_start_pos:60 SignalNormalisationParams { strategy:pa StandardisationScalingParams { standardise:1 mean:80.875900 stdev:17.269760}} BasecallerParams { chunk_size:18432 overlap:492 batch_size:0} convs: { 0: ConvParams { insize:1 size:64 winlen:5 stride:1 activation:swish} 1: ConvParams { insize:64 size:64 winlen:5 stride:1 activation:swish} 2: ConvParams { insize:64 size:128 winlen:9 stride:3 activation:swish} 3: ConvParams { insize:128 size:128 winlen:9 stride:2 activation:swish} 4: ConvParams { insize:128 size:512 winlen:5 stride:2 activation:swish}} model_type: tx { crf_encoder: CRFEncoderParams { insize:512 n_base:4 state_len:5 scale:5.000000 blank_score:2.000000 expand_blanks:1 permute:1} transformer: TxEncoderParams { d_model:512 nhead:8 depth:18 dim_feedforward:2048 deepnorm_alpha:2.449490}}}
[2024-05-25 13:39:39.694] [info]  - BAM format does not support `U`, so RNA output files will include `T` instead of `U` for all file types.
[2024-05-25 13:39:44.394] [debug] cuda:2 memory available: 33.33GB
[2024-05-25 13:39:44.394] [debug] cuda:2 memory limit 32.33GB

...

[2024-05-25 13:40:03.016] [debug] Load reads from file /data/20240328_2254_P2S-00909-B_PAU42445_0a472f31/pod5/PAU42445_0a472f31_ca3b749f_268.pod5
terminate called after throwing an instance of 'c10::Error'asecalling                                                                                                                                
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/pyold/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x14aa8c3039b7 in /g/data/lf10/as7425/apps/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x14aa85888115 in /g/data/lf10/as7425/apps/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x14aa8c2cd958 in /g/data/lf10/as7425/apps/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #3: <unknown function> + 0x897b516 (0x14aa8a246516 in /g/data/lf10/as7425/apps/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #4: c10::Stream::synchronize() const + 0x82 (0x14aa8c2e0de2 in /g/data/lf10/as7425/apps/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #5: ./dorado() [0xa59018]
frame #6: <unknown function> + 0x1196e380 (0x14aa93239380 in /g/data/lf10/as7425/apps/dorado-0.7.0-linux-x64/bin/../lib/libdorado_torch_lib.so)
frame #7: <unknown function> + 0x81ca (0x14aa810691ca in /lib64/libpthread.so.0)
frame #8: clone + 0x43 (0x14aa7fa2de73 in /lib64/libc.so.6)

Aborted

**Comment by tijyojwad** [comment]
Hi @pre-mRNA - thanks for reporting. We've had a couple of others reports of this and are investigating. Could you try running with only 1 mod e.g. `sup, m6A` and see if that runs further? From other users that appears to be working.

**Comment by AnWiercze** [comment]
Hi,
We encountered the same problem. When specifying multiple GPUs, the same error message appeared. 

`dorado basecaller rna004_130bps_sup@v5.0.0 $pod5_dir --modified-bases pseU -r --device "cuda:0,cuda:1" > test.bam`

The error disappeared when we specified exactly one GPU, however, we now received a different message for the following command and the runtime is now expected to be >1day:

`dorado basecaller rna004_130bps_sup@v5.0.0 $pod5_dir --modified-bases pseU -r --device "cuda:0" > test.bam`

```
[2024-05-27 09:24:35.678] [warning] Could not determine sequencing Chemistry from read data - some features might be disabled 
[▏                             ] 0% [13m:32s<01d:06h:28m:35s] Basecalling        
```

Thanks a lot for your help! 

Best, 
Anna

**Comment by tijyojwad** [comment]
Hi @AnWiercze thanks for reporting your findings. The `[warning] Could not determine sequencing Chemistry from read data` is a warning and will not affect your output. But we'll look into the multi GPU aspect of the bug.

**Comment by pre-mRNA** [comment]
I get the same error whether I basecall with one GPU or several. 

However, if I only try to basecall one base, e.g. pseudoU, it seems to work fine.

**Comment by pre-mRNA** [comment]
> * i would just try to set the batch size manually to something sensible and check if that fixes it?
>   **edited2**
>   -` ~/dorado-0.7.0-linux-x64/bin/dorado basecaller ~/models/rna004_130bps_sup@v5.0.0 ./UHRR_pod5_test/ -b 320 --device "cuda:0,cuda:1" --modified-bases pseU > ./test_UHRR_output/test.bam`
>   -setting the batch size to this does allow to run without crashing; its not optimal in terms of ressources; but it does allow us to run all tested configs without crashing at least


That worked great on my system. I get ~100% GPU utilisation and the basecalling (including pseudoU and m6A mod calls) completes without any issues. 

Thanks!

**Comment by HalfPhoton** [comment]
@pre-mRNA 
Can you also try `--chunksize 9996`?
This may further reduce memory consumption.

**Comment by pre-mRNA** [comment]
Hi, I'm now working with Dorado 0.7.2

No combination of chunksize and batchsize allows the basecalling to complete.

The command I am using (while iterating over chunksize & batchsize) is: 

```
dorado basecaller sup,m6A,pseU $data_dir --chunksize 9996 -b 320 --estimate-poly-a
```

The command works find if I only call one modification at a time.

**Comment by HalfPhoton** [comment]
Sorry to hear you're still having difficulties.
We're working on improving the performance of the new sup model architecture and modbase models to improve the situation in the future.

**Comment by malton-ont** [comment]
@pre-mRNA, can you please try dorado 0.8.0? We believe we have addressed a couple of issues that should resolve this error.

**Comment by pre-mRNA** [comment]
Yes, this is with Dorado 0.8.0.

Previously, even tuning batch size wouldn't work with Dorado 0.7.x when calling multiple modifications on my cluster.


________________________________

**Comment by caspargross** [comment]
I can confirm that this error still appears in v.0.8.0 It is the same as reported in my previous issue https://github.com/nanoporetech/dorado/issues/850

**Comment by HalfPhoton** [comment]
@caspargross,
Does this issue persist in 0.9.0+ which has a new modbase model architecture which improved performance? 

Kind regards,
Rich

**Comment by samim21** [comment]
I am having this issue with 0.9.1 with the sup 5mCG_5hmCG and hac 5mCG_5hmCG models for DNA.
